from .spooky_categorial_predicate import SpookyCategorialPredicate
from .spooky_numerical_predicate import SpookyCompareOperation, SpookyNumericalPredicate
from .spooky_predicate import SpookyPredicate
